---
- name: Wait up to 5 minutes until site is up
  uri:
    url: '{{ public_protocol }}://{{ http_hostname }}'
    validate_certs: False
  register: site_check
  retries: 60
  delay: 5
  until: site_check.status is defined and site_check.status == 200

- debug:
    msg: 'ERROR site_check.status undefined accessing {{ public_protocol }}://{{ http_hostname }}'
  when: site_check.status is not defined

- debug:
    msg: 'ERROR {{ site_check.status }} accessing {{ public_protocol }}://{{ http_hostname }}'
  when: site_check.status != 200

- debug:
    msg: '{{ public_protocol }}://{{ http_hostname }} is OK'
  when: site_check.status is defined and site_check.status == 200
