version: '2.2'
services:
  django:
    environment:
      DEBUG: 'True'
      SITEURL: http://{{ site_hostname }}/
      ALLOWED_HOSTS: "[{{ site_hostname }}]"
      GEOSERVER_PUBLIC_LOCATION: http://{{ site_hostname }}/gs/

  celery:
    environment:
      DEBUG: 'True'
      SITEURL: http://{{ site_hostname }}/
      ALLOWED_HOSTS: "[{{ site_hostname }}]"
      GEOSERVER_PUBLIC_LOCATION: http://{{ site_hostname }}/gs/

  geoserver:
    environment:
      NGINX_BASE_URL: http://{{ site_hostname }}:80

volumes:
  geoserver-data-dir:
    name: '{{ gsdata }}'
  dbdata:
    name: '{{ postgres_data_directory }}'
  dbbackups:
    name: '{{ backup_dir }}'
  statics:
    name: '{{ ansible_env.HOME }}/{{ project_dir }}/{{ project_dir }}/{{ org }}/{{ project_name }}/static'
