version: '2.2'
services:
  django:
    environment:
      DEBUG: 'True'
      SITEURL: http://{{ site_hostname }}/
      ALLOWED_HOSTS: "[{{ site_hostname }}]"
      GEOSERVER_PUBLIC_LOCATION: http://{{ site_hostname }}/gs/

  celery:
    environment:
      DEBUG: 'True'
      SITEURL: http://{{ site_hostname }}/
      ALLOWED_HOSTS: "[{{ site_hostname }}]"
      GEOSERVER_PUBLIC_LOCATION: http://{{ site_hostname }}/gs/

  geoserver:
    environment:
      NGINX_BASE_URL: http://{{ site_hostname }}:80

volumes:
  - '{{ gsdata }}': geoserver-data-dir
      name: gsdata
  - '{{ postgres_data_directory }}': dbdata
      name: dbdata
  - '{{ backup_dir }}': dbbackups
      name: dbbackups
  - '{{ ansible_env.HOME }}/{{ project_dir }}/{{ project_dir }}/{{ org }}/{{ project_name }}/static': /statics
    name: statics
  - '{{ ansible_env.HOME }}/{{ project_dir }}/{{ project_dir }}/': /uploaded
    name: uploaded
