---
- name: Create virtualenv dir
  file:
    path: "{{ lookup('env','HOME') }}/.virtualenvs"
    state: directory

- name: Install virtualenv and wrapper
  pip:
    name:
      - virtualenv
      - virtualenvwrapper
  become: true

- name: Trigger virtualenv from user's bash run commands
  blockinfile:
    path: "{{ lookup('env','HOME') }}/.bashrc"
    block: |
      export WORKON_HOME=$HOME/.virtualenvs
      source /usr/local/bin/virtualenvwrapper.sh
      export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python
      export VIRTUALENVWRAPPER_VIRTUALENV=/usr/local/bin/virtualenv
      export SITE_HOST_NAME={{ private_ip }}
      export SITE_HOST_PORT={{ port }}


# export PROJECT_HOME=$HOME/
# export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='--no-site-packages'
