---
- name: Git Geonode
  git:
    repo: https://github.com/GeoNode/geonode
    dest: '{{ ansible_env.HOME }}/geonode'
  # ignore_errors: True
  # no_log: True

# - name: rename subdir to project_dir
#   command: mv geonode-project {{ project_dir }}
#   args:
#     chdir: '{{ ansible_env.HOME }}/{{ project_dir }}'
#     creates: '{{ ansible_env.HOME }}/{{ project_dir }}/{{ project_dir }}'
#
# - name: Template geonode-project files from Ansible Control to server
#   template:
#     src: '{{ item }}'
#     dest: '~/{{ project_dir }}/{{ project_dir }}/'
#   with_fileglob:
#     - '{{ playbook_dir }}/geonode-project/*.py'
#     - '{{ playbook_dir }}/geonode-project/*.py.sample'
#
# - name: Template home dir files from Ansible Control to server
#   template:
#     src: '{{ item }}'
#     dest: '~/{{ project_dir }}/'
#   with_fileglob:
#     - '{{ playbook_dir }}/.env'
#     - '{{ playbook_dir }}/docker*.yml'
#     - '{{ playbook_dir }}/Dockerfile'
#     - '{{ playbook_dir }}/*.py'
#     # - '{{ playbook_dir }}/playbook.yml'
#     - '{{ playbook_dir }}/uwsgi.ini'

- name: Duplicate localhost override for private IP
  command: cp docker-compose.override.localhost.yml docker-compose.override.{{ http_hostname }}.yml
  args:
    chdir: '{{ ansible_env.HOME }}/geonode'
    creates: '{{ ansible_env.HOME }}/geonode/docker-compose.override.{{ http_hostname }}.yml'

- name: Set private IP address as host
  replace:
    path: '{{ ansible_env.HOME }}/geonode/docker-compose.override.{{ http_hostname }}.yml'
    regexp: localhost
    replace: '{{ http_hostname }}'

- name: Refresh private_ip var
  include_vars: group_vars/{{ envt }}

- name: Launch the stack
  command: docker-compose -f docker-compose.yml -f docker-compose.override.{{ http_hostname }}.yml up --build
  args:
    chdir: '{{ ansible_env.HOME }}/geonode'
  ignore_errors: True
  no_log: True

# - name: Prepare the stack (without running) 2/2
#   command: docker-compose -f docker-compose.yml up --no-start
#   args:
#     chdir: '{{ ansible_env.HOME }}/{{ project_dir }}'
#   become: true
#
# - name: Start the database
#   command: docker-compose -f docker-compose.yml up -d db
#   args:
#     chdir: '{{ ansible_env.HOME }}/{{ project_dir }}'
#   become: true
#
# - debug: msg="{{ lookup('env','PATH') }} is an environment variable"
#
# - name: Initialise geoserver
#   command: docker-compose -f docker-compose.yml run --rm geoserver true
#   args:
#     chdir: '{{ ansible_env.HOME }}/{{ project_dir }}'
#     executable: /bin/bash
#   become: true
