---
- name: Git Geonode
  git:
    repo: https://github.com/GeoNode/geonode
    dest: ~/geonode
    force: True

- name: Set project name for docker
  replace:
    path: ~/geonode/.env
    regexp: ^\s*COMPOSE_PROJECT_NAME\s*=.*$
    replace: COMPOSE_PROJECT_NAME={{ project_name }}

- name: Create project directory
  file:
    path: ~/{{ project_dir }}
    state: directory

- name: Template docker-compose override files
  template:
    src: '{{ item }}.j2'
    dest: ~/{{ project_dir }}/{{ item }}
  with_items:
    - docker-compose.override-hostname.yml
    - docker-compose.override-volumes.yml
    - docker-compose.override-debug.yml

- name: Create folders for docker volumes
  file:
    name: '{{ item }}'
    state: directory
  with_items:
    - '{{ statics_dir }}'
    - '{{ log_dir }}/nginx'
  become: True

# - name: Refresh private_ip var
#   include_vars: group_vars/{{ envt }}

- name: Link geoserver log to logs directory
  file:
    src: '{{ gsdata }}/logs/'
    dest: '{{ log_dir }}/geoserver'
    state: link
    force: True
    follow: False
  become: True

- name: Wait for docker daemon to start
  wait_for:
    # port: 2375
    path: /var/run/docker.pid
    # delay: 10
    timeout: 600

# cd ~/geonode && docker-compose -f docker-compose.yml -f ~/citydata/docker-compose.override-hostname.yml -f ~/citydata/docker-compose.override-volumes.yml -f ~/citydata/docker-compose.override-debug.yml up --build
- name: Launch the stack
  command: >
    docker-compose
      -f docker-compose.yml
      -f ~/{{ project_dir }}/docker-compose.override-hostname.yml
      -f ~/{{ project_dir }}/docker-compose.override-volumes.yml
      -f ~/{{ project_dir }}/docker-compose.override-debug.yml
      up --build
  args:
    chdir: ~/geonode
  # ignore_errors: True
  # no_log: True

# Commented because it requires modules installed (in roles/prep_server)
# which failed with fatal error: ffi.h: No such file or directory
# - name: Launch the stack
#   docker_service:
#     project_src: ~/{{ project_dir }}
#     files:
#       - docker-compose.override.yml
#     build: yes
#   become: True
#   environment:
#     PYTHONPATH: "{{ lookup('env','PYTHONPATH') }}:/usr/lib/python2.7/dist-packages"

# - name: Prepare the stack (without running) 2/2
#   command: docker-compose -f docker-compose.yml up --no-start
#   args:
#     chdir: '{{ ansible_env.HOME }}/{{ project_dir }}'
#   become: true
#
# - name: Start the database
#   command: docker-compose -f docker-compose.yml up -d db
#   args:
#     chdir: '{{ ansible_env.HOME }}/{{ project_dir }}'
#   become: true
#
# - debug: msg="{{ lookup('env','PATH') }} is an environment variable"
#
# - name: Initialise geoserver
#   command: docker-compose -f docker-compose.yml run --rm geoserver true
#   args:
#     chdir: '{{ ansible_env.HOME }}/{{ project_dir }}'
#     executable: /bin/bash
#   become: true
