---
- name: Launch the stack asynchronously
  shell: >
    docker-compose
    -f docker-compose.yml
    -f ~/{{ project_dir }}/docker-compose.override.hostname.yml
    -f ~/{{ project_dir }}/docker-compose.override.volumes.yml
    -f ~/{{ project_dir }}/docker-compose.override.django-env.yml
    up --build
  async: 600
  poll: 0
  args:
    chdir: ~/geonode

- name: Wait up to 5 minutes for django container to start
  shell: docker ps | grep -q 'Up.*django4{{ project_name }}'
  retries: 60
  delay: 5
  register: result
  until: result is succeeded

- name: Copy geonode to containers
  command: docker cp . {{ item }}4{{ project_name }}:/usr/src/app
  with_items:
    - django
    - celery
  args:
    chdir: ~/geonode
