---
- name: Install custom static and template files
  copy:
    src: '{{ playbook_dir }}/geonode-project/{{ org }}/{{ project_dir }}/{{ item }}/'
    dest: ~/{{ project_dir }}/{{ project_dir }}/{{ item }}
  with_items:
    - static
    - templates

- name: Copy custom files to be served by Apache
  django_manage:
    app_path: '~/{{ project_dir }}'
    command: collectstatic
    virtualenv: ~/.virtualenvs/{{ project_dir }}

- name: Set page title
  replace:
    path: ~/{{ project_dir }}/{{ project_dir }}/templates/site_base.html
    regexp: INSERT_PROJECT_HERE
    replace: '{{ project }}'

- name: Restart Django
  file:
    path: ~/{{ project_dir }}//{{ project_dir }}/wsgi.py
    state:  touch
