---
# Commands moved to docker_geonode role
# Commented these tasks because we should do it with docker commands
#
# - name: Copy custom files to be served by Apache
#   django_manage:
#     app_path: '~/{{ project_dir }}'
#     command: collectstatic
#     virtualenv: ~/.virtualenvs/{{ project_dir }}
#
# - name: Restart Django
#   file:
#     path: ~/{{ project_dir }}//{{ project_dir }}/wsgi.py
#     state:  touch
