---
- name: Install custom static and template files
  copy:
    src: '{{ playbook_dir }}/geonode-project/{{ org }}/{{ project_dir }}/{{ item }}/'
    dest: ~/{{ project_dir }}/geonode-project/{{ item }}
  with_items:
    - static
    - templates

- name: Set page title
  replace:
    path: ~/{{ project_dir }}/geonode-project/templates/site_base.html
    regexp: INSERT_PROJECT_HERE
    replace: '{{ project }}'


# Commented these tasks because we should do it with docker commands
#
# - name: Copy custom files to be served by Apache
#   django_manage:
#     app_path: '~/{{ project_dir }}'
#     command: collectstatic
#     virtualenv: ~/.virtualenvs/{{ project_dir }}
#
# - name: Restart Django
#   file:
#     path: ~/{{ project_dir }}//geonode-project/wsgi.py
#     state:  touch
