---
- name: Generate SSH key
  shell: ssh-keygen -f ~/.ssh/id_rsa -N ''
  args:
    creates: ~/.ssh/id_rsa.pub
  delegate_to: '{{ data_src }}'

- name: Read public key
  shell: cat ~/.ssh/id_rsa.pub
  register: key
  delegate_to: '{{ data_src }}'

- name: Authorise the key
  authorized_key:
    key: '{{ key.stdout_lines[0] }}'
    user: '{{ ansible_user_id }}'

- name: Push database backup from source server
  synchronize:
    src: '{{ backup_dir }}/pg_dumpall.custom'
    dest: '{{ backup_dir }}/pg_dumpall.custom'
  delegate_to: '{{ data_src }}'

- name: Push uploaded files from source server
  synchronize:
    src: '{{ big_dir }}/geonode/geonode/geonode/uploaded/'
    dest: ~/{{ project_dir }}/{{ project_dir }}/uploaded/
  delegate_to: '{{ data_src }}'
  become: True

- name: Push geoserver data from source server
  synchronize:
    src: '{{ big_dir }}/geoserver_data/'
    dest: '{{ gsdata }}/'
  delegate_to: '{{ data_src }}'
  become: True
