---

- include_tasks: set_hostname.yml

- include_tasks: set_timezone.yml

- include_tasks: mount_disk.yml

- name: Check tmp folder
  stat:
    path: /tmp
  register: tmp_check

- include_tasks: mv_tmp_to_big_disk.yml
  when: "tmp_check.stat.islnk is not defined or (tmp_check.stat.islnk is defined and tmp_check.stat.islnk == False) and 'small_sysdisk' in group_names"

- include_tasks: install_docker.yml

- name: Check docker folder
  stat:
    path: /var/lib/docker
  register: docker_check

- include_tasks: mv_docker_to_big_disk.yml
  when: "docker_check.stat.islnk is not defined or (docker_check.stat.islnk is defined and docker_check.stat.islnk == False)"

- name: Create data dirs
  file:
    path: '{{ item }}'
    state: directory
  become: true
  with_items:
    - '{{ gsdata }}'
    - '{{ postgres_data_directory }}'
