---
- name: Allow access to dump dir
  file:
    path: /mnt/backup
    mode: 0777

- name: Trust connection from localhost
  replace:
    path: /etc/postgresql/9.5/main/pg_hba.conf
    regexp: 'host\s+all\s+all\s+127.0.0.1/32\s+md5'
    replace: 'host    all             all             127.0.0.1/32            trust'
  become: true

- name: Restart postgres
  service:
    name: postgresql
    state: restarted
  become: true

# Dump the database content (you will be prompted several time for the password above)

- name: Dump the database
  command: 'pg_dumpall --host=127.0.0.1 --file=pg_dumpall.custom'
  args:
    chdir: /mnt/backup
  become_user: postgres
  become: true
